apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls
  namespace: default
spec:
  secretName: app-tls

  issuerRef:
    kind: ClusterIssuer
    name: duckdns-letsencrypt-prod

  dnsNames:
    - app.your-subdomain.duckdns.org