# This has to be deployed manually at first. Use kubectl apply -f parent-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chris-ab25/homelab'
    targetRevision: main
    path: '4. apps/parent-apps'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true