apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-duckdns-cert
  namespace: gateway-system
spec:
  secretName: wildcard-duckdns-cert
  issuerRef:
    name: duckdns-letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.chrisab25.duckdns.org"