apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        parameters:
          - name: crds.enabled
            value: "true"
   # - repoURL: https://github.com/chris-ab25/homelab
   #   targetRevision: main
   #   path: '4. apps/child-apps/certmanager'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy: {}